### ISSUE TITLE
Compatible with RGB images?

### ISSUE THREAD

**Issue by ajinkya-kulkarni** [ghadialhajj/FF_unsupervised#2]
Hi, thanks for the repo! I was wondering if this package is compatible with a generic RGB dataset with labels for each image. Something like a CIFAR10 for example.

**Comment by ghadialhajj** [comment]
Hi :) thanks for your question.

Technically, yes, that is possible given that the code automatically reshapes the input images into a vector which should match input_size (see __init__ of Unsupervised_FF). Specifically, in lines 96 and 97 in main.py, the input image is reshaped to [batch_size, 1, -1]. 

This, however, would not be conceptually in line with RGB images since it doesn't keep the three dimensions separate.  Additionally, even if you resize to [batch_size, 3, -1], this will not work when it comes to the layer normalisation, LN, part, at least not with the current code, because LN expects to receive a vector of shape [1, layer_size].

To make it work, you can manually change the LN part in line 45 to accept [3, layer_size] inputs and make sure to set the input size to the size (i.e. numel not shape) of a given CIFAR image anyway :)
